In [5]:

import os
import sys
sys.path.append('/home/psavine/source/viper')
sys.path.append("../")

import matplotlib
import numpy as np
import shapely
import spec.hvac
import importlib
# importlib.reload(spec.viper)


/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2917: RuntimeWarning: Mean of empty slice.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)


layers :1172 
centroids: 1172 
starts: 1173 
Counter({0: 496, 2: 346, 1: 279, 3: 15, 5: 6, 4: 3})


In [12]:
importlib.reload(spec.hvac)
T = spec.hvac.TestHvacSys()
T.setUp()
system, solids = T.test_buildnl()

/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2917: RuntimeWarning: Mean of empty slice.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)


layers :1172 
centroids: 1172 
starts: 1173 


1172it [00:00, 2249.24it/s]


Counter({2: 476, 0: 372, 1: 259, 3: 61, 4: 4})


In [17]:
from collections import Counter
import src.geom
importlib.reload(src.ui.visual)
importlib.reload(src.geom)

def prebox(solids):
    meshes = []
    for s in solids:
        s.process()
        try:
            b = s.bounding_box_oriented
            b._create_mesh()
            meshes.append(s)
        except:
            meshes.append(None)
    return meshes


def make_bbx_conns(connectivity, objects, handle=None):
    seen_ = set()
    # check how good estimate is -- and visualize !

    for k, v in connectivity.items():  
        solid = solids[k]
        if solid is None:
            continue
        
        for i in v: 
            
            hsh = tuple(sorted([k, i]))
            if hsh not in seen_:
                seen_.add(hsh)
                neigh = solids[i]
                if neigh is None:
                    continue
                try:
                    c1, c2 = src.geom.connector_face(solid, neigh)

                    c1 = c1[~np.isnan(c1)]
                    c2 = c2[~np.isnan(c2)]
                    print(c1, c2)
                    if c2.size == 3:
                        src.ui.visual.line_hull(neigh.centroid, c2, handle=handle, viz=VIZ)
                    if c1.size == 3:
                        src.ui.visual.line_hull(solid.centroid, c1, handle=handle, viz=VIZ)

                except:
                    print('err')

In [18]:
reps = prebox(solids)


In [19]:
make_bbx_conns(system.res, reps, handle='conn')

[757.50387968 -18.25966203  -1.92249228] [754.14000843 -21.95890118  -1.92249228]
err
[754.14000843 -21.95890118  -1.92249228] []
err
[754.14000843 -21.95890118  -1.92249228] []
err
[] [758.59861272 -23.5209318   -1.91665897]
err
[] []
[] [759.34861272 -24.9740568   -1.91665897]
err
[] [759.34861272 -24.9740568   -1.91665897]
err
[] [750.66111272 -17.0834318   -1.91665802]
err
[] [750.66111272 -17.0834318   -1.91665802]
err
[751.56736272 -22.1771818   -1.91665802] [749.84861272 -18.3881193   -1.91665802]
err
[751.47361272 -20.4506193   -1.91665802] []
err
[754.07361272 -24.6443693   -1.81665973] [758.01111272 -25.9724943   -1.81665973]
err
[755.75486272 -24.3959318   -1.91665802] []
err
[777.09861272  -7.6224943   -6.33334169] []
err
[777.75486272  -8.2084318   -5.45413312] []
err
[] [777.09861272  -7.6224943   -1.31662044]
err
[] []
[] [778.41111272  -8.7865568   -8.9166542 ]
err
[] [778.59861272  -8.9662443   -1.23323783]
err
[778.64548772  -8.99358805  -8.08231673] []
err
[] []
[778

/home/psavine/source/viper/src/geom.py:495: RuntimeWarning: Mean of empty slice.
  center = mesh.vertices[unique_v].mean(axis=0)
/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)


[] [761.81736272   6.2290682   -5.91391668]
err
[] []
[] [760.91111272   7.0650057   -5.53853759]
err
[761.28611272   6.7212557   -3.99873409] []
err
[760.03611272   7.8540682   -3.57957563] []
err
[] []
[] []
[] [742.37986272  -6.45322347  -2.80897261]
err
[] []
[] []
[740.94236272  -7.9037443   -2.98961982] []
err
[] []
[] []
[] []
[733.84861272 -23.0209318   -1.75001678] []
err
[] []
[] []
[] []
[] []
[] []
[] [ 7.52004863e+02 -6.61556800e-01 -1.49999103e+00]
err
[751.12986272   3.90484945  -2.26562557] []
err
[] []
[] []
[] []
[] []
[] [765.53611272   6.5025057   -1.23330078]
err
[] []
[] []
[761.28611272   6.4556307   -1.23330078] []
err
[] []
[] []
[] []
[] []
[] []
[] []
[] []
[] []
err
[] []
[] [740.19236272 -13.3178068   -6.08342514]
err
[] [740.19236272 -13.3178068   -8.88342533]
err
[] [738.06736272 -11.3178068   -8.88342533]
err
[] [738.06736272 -11.3178068   -6.08342514]
err
[] [738.06736272 -11.3178068   -8.88342533]
err
[] [738.06736272 -11.3178068   -8.88342533]
err
err

/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/trimesh/ray/ray_triangle.py:320: RuntimeWarning: divide by zero encountered in true_divide
  t = (axis_bound - axis_ori) / axis_dir
/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/trimesh/ray/ray_triangle.py:333: RuntimeWarning: invalid value encountered in multiply
  on_b = (ray_directions * t_b) + ray_origins
/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/home/psavine/anaconda3/envs/viper/lib/python3.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


err
[733.94236272  15.5103182   -2.01547489] []
err
[734.26111272  15.5618807   -1.99980793] []
err
[733.19236272  13.1196932   -1.41649112] []
err
[] []
[] []
[6.49036113e+02 5.49009432e+01 2.87512212e-01] []
err
[ 6.49567363e+02  5.54946932e+01 -5.08312793e-01] []
err
[] []
[] []
[] []
[] [7.04004863e+02 5.13531820e+00 1.29107861e-01]
err
[ 7.04536113e+02  5.72125570e+00 -6.66754337e-01] []
err
[] []
[] []
[] []
[] []
[] []
[] []
[] []
[] []
[] []
[] [767.87986272 -38.4506193   -1.83335075]
err
[] []
[] []
[766.22361272 -39.60296305  -1.50002155] []
err
[] [765.53611272 -41.1537443   -1.83333358]
err
[766.69236272 -39.0756193   -1.83752498] [765.62986272 -41.6381193   -1.83333263]
err
[765.37986272 -39.7006193   -1.83333263] []
err
[765.46111272 -40.0631193   -1.76666698] []
err
[] []
[] []
[] []
[] []
[] []
[] [777.47361272 -23.1224943   -1.8333498 ]
err
[787.84861272   4.1040682   -1.83740005] []
err
[] []
[762.00486272 -16.6068693   -2.04579124] []
err
[762.00486272 -16.6068693   

[] []
[] []
[] []
[] []
[] []
[] []
[] [ 6.99598613e+02  1.09424381e+02 -6.66658015e-01]
err
[] []
[711.11423772  87.41266195   1.41666737] []
err
[] []
[] [715.52048772  92.2525057   -0.91664943]
err
[] [ 7.16723613e+02  9.35806307e+01 -5.83325000e-01]
err
[716.48923772  93.31891195  -0.91664943] []
err
[] []
[] [631.81736272  89.6353182   -1.9166418 ]
err
[] []
[] []
[] []
[] []
[] [631.41111272  65.3071932   -1.833325  ]
err
[] [631.41111272  65.3071932   -1.833325  ]
err
[] []
[] []
[626.84861272  60.2993807   -1.83328304] []
err
[625.75486272  60.0181307   -1.83333358] []
err
[755.83298772  11.6743807   -2.26567516] []
err
[753.59861272  13.80328695  -1.00404605] []
err
[754.25486272  13.2134432   -2.15407047] []
err
[] []
[] []
[724.97361272  78.3853182    1.41682568] []
err
[] []
[] []
[] []
[] []
[ 7.14723613e+02  9.94165682e+01 -5.83325000e-01] []
err
[ 7.14379863e+02  9.90298495e+01 -1.66658969e-01] [716.22361272  97.1743807   -6.82290802]
err
[] []
[] []
[] [758.09861272 -44